### ISSUE TITLE
SQL Error during app activation: 1071 Specified key was too long; max key length is 3072 bytes

### ISSUE THREAD

**Issue by kaceel** [michib/nextcloud_twofactor_webauthn#19]
Upon trying to activate this app I get an SQL error:

An exception occurred while executing 'CREATE TABLE oc_twofactor_webauthn_registrations (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(64) DEFAULT 'default' NOT NULL, public_key_credential_id VARCHAR(4000) NOT NULL, type VARCHAR(255) NOT NULL, transports VARCHAR(255) NOT NULL, attestation_type VARCHAR(255) NOT NULL, trust_path VARCHAR(255) NOT NULL, aaguid VARCHAR(255) DEFAULT NULL, credential_public_key VARCHAR(4000) NOT NULL, user_handle VARCHAR(64) NOT NULL, counter INT NOT NULL, INDEX webauthn_registrations_userHandle (user_handle), INDEX webauthn_registrations_publicKeyCredentialId (public_key_credential_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes

nextcloud version is 16.0.4.1

Database is mysql 5.7.27,  innodb_file_format | Barracuda, innodb_file_per_table | ON

**Comment by do1mps** [comment]
I got the same error while first-Installing this Plugin.
Nextcloud 16.0.4
Update-Channel Stable
Error occures while installing or activating.
After Error the Plugin seems to be available, but activating is impossible too.

An exception occurred while executing 'CREATE TABLE oc_twofactor_webauthn_registrations (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(64) DEFAULT 'default' NOT NULL, public_key_credential_id VARCHAR(4000) NOT NULL, type VARCHAR(255) NOT NULL, transports VARCHAR(255) NOT NULL, attestation_type VARCHAR(255) NOT NULL, trust_path VARCHAR(255) NOT NULL, aaguid VARCHAR(255) DEFAULT NULL, credential_public_key VARCHAR(4000) NOT NULL, user_handle VARCHAR(64) NOT NULL, counter INT NOT NULL, INDEX webauthn_registrations_userHandle (user_handle), INDEX webauthn_registrations_publicKeyCredentialId (public_key_credential_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes

**Comment by michib** [comment]
Thanks for the feedback. I will look into it on the weekend.

**Comment by do1mps** [comment]
Thanks a lot for that!

**Comment by michib** [comment]
I tested it locally with a docker-compose setup with nextcloud 16.0.4 and mysql 5.7.27 and was able to reproduce the issue and also was able to activate the plugin after the fix

**Comment by michib** [comment]
Sorry for the incredible long delay. @do1mps I uploaded 0.1.1-alpha.1 which should fix your isse
