### ISSUE TITLE
Windows Hello Webauthn log in does not work

### ISSUE THREAD

**Issue by army1349** [michib/nextcloud_twofactor_webauthn#21]
You can add webauthn device using Windows Hello Webauthn using fingerprint just fine.
But when you try to log in, validation fails and it keeps asking for fingerprint.

**Comment by michib** [comment]
Is your setup nextcloud ^16.0 and mysql? I can reproduce the issue on this setup with a yubikey. I does not have a possibility to test windows hello

**Comment by army1349** [comment]
It is Nextcloud 16 (17 now and same issue), PHP 7.3, MariaDB 10.3

**Comment by dcshoes23** [comment]
I am experiencing the same issue with NC 18.0.2 and twofactor_webauthn: 0.1.2.

It just keeps looping and asking for Windows Hello authorziation

**Comment by michib** [comment]
Can you both check the nextcloud server log if there is an exception when you try to add windows hello as webauthn device? Unfortunately i cannot test it myself

**Comment by dcshoes23** [comment]
I didn't see any errors in the log, I then enabled debug logging and this is all I see:

> [no app in context] Debug: Deprecated event type for OCP\Authentication\TwoFactorAuth\IProvider::failed: Symfony\Component\EventDispatcher\GenericEvent
> 
> POST /login/challenge/twofactor_webauthn?redirect_url=/apps/files/

**Comment by army1349** [comment]
> 
> 
> Can you both check the nextcloud server log if there is an exception when you try to add windows hello as webauthn device? Unfortunately i cannot test it myself

Now even if I register device, no device is requested and I can log in with just password.
Active option is checked. Nothing in logs.

**Comment by michib** [comment]
@army1349 What do you mean with: "Now even if i register device"? The registration is successful?
Cause you are seeing the "active" option i image you are using the 0.2.0-alpha version?
There is a bug that causes the provider not to be active, even if there are active devices. See Issue #33. This bug is nearly fixed and i hope i can provide a new version this evening

**Comment by michib** [comment]
Could you send me a dump of the twofactor_webauthn_registrations table of your nextcloud database. It would be really helpful if i could examine the entries

**Comment by army1349** [comment]
> 
> 
> @army1349 What do you mean with: "Now even if i register device"? The registration is successful?
> Cause you are seeing the "active" option i image you are using the 0.2.0-alpha version?

Yes, registration was successful and I am using version 0.2.0.
I got this version via regular nextcloud app update.

> There is a bug that causes the provider not to be active, even if there are active devices. See Issue #33. This bug is nearly fixed and i hope i can provide a new version this evening

I see, so I will wait for that fix and try it then.
I tried version 0.1.2 in past with same result as @dcshoes23.

**Comment by dcshoes23** [comment]
> Could you send me a dump of the twofactor_webauthn_registrations table of your nextcloud database. It would be really helpful if i could examine the entries

Emailed you the dump

**Comment by michib** [comment]
Great, thank you both for your feedback. It's really appreciated. I hope i will be able to look into it this week.

**Comment by army1349** [comment]
Nice work! Version 0.2.1 works for me.

**Comment by michib** [comment]
@army1349 Oh that's great to hear. Also a little bit surprising, i didn't expect the last two bug fixes to solve your problem. But nevertheless, i'm glad it works now for you :-)

@dcshoes23 Can you check if 0.2.1 also works for you?

**Comment by army1349** [comment]
> 
> 
> @army1349 Oh that's great to hear. Also a little bit surprising, i didn't expect the last two bug fixes to solve your problem. But nevertheless, i'm glad it works now for you :-)

Thanks, man.

**Comment by dcshoes23** [comment]
I second that everything works fine now with 0.2.1. I did have to remove and re-add my Windows Hello webauthn registration, but after that, all works well. Thanks so much for making this app and for fixing our issues!

**Comment by michib** [comment]
Great, thanks four your feedback. It's really highly appreciated to get this provider into a stable state.

So i regard this issue fixed by #34
