### ISSUE TITLE
SQL DriverException: Character not in repertoire, invalid byte sequence for encoding

### ISSUE THREAD

**Issue by stuehmer** [michib/nextcloud_twofactor_webauthn#22]
When adding a YubiKey device I get no response from the UI: the spinner keeps spinning after entering a name for the new device.

The problem seems to be the value for column `aaguid` in table `oc_twofactor_webauthn_registrations` which cannot be inserted successfully into the database.

My setup:
- The database is Postgres 11.5 on Debian.
- Nextcloud 16.0.4
- Two-Factor Webauthn 0.0.1 installed via the store

In `nextcloud.log` find the following: (I added some `XX`)
```
"An exception occurred while executing 'INSERT INTO \"oc_twofactor_webauthn_registrations\"
(\"name\", \"public_key_credential_id\", \"type\", \"transports\", \"attestation_type\", \"trust_path\", \"aaguid\", \"credential_public_key\", \"user_handle\", \"counter\") VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"YubiKey 1 USB-C\", \"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXrTzQJ7\\/7sS7HyDs=\", \"public-key\", \"[]\", \"none\", \"{\\\"type\\\":\\\"empty\\\"}\", \"\\x60\\x28\\xb0\\x17\\xb1\\xd4\\x4c\\x02\\xb4\\xb3\\xaf\\xcdXXXXXXXXXXXXXXXXXXXXX", \"pAEDAzkBACBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXhKhIUMBAAE=\", \"admin\", 0]:\n\nSQLSTATE[22021]: Character not in repertoire: 7 ERROR:  invalid byte sequence for encoding \"UTF8\": 0xb0"
```

**Comment by michib** [comment]
I uploaded Version 0.1.1-alpha.1. Can you check if the problem still exists with this version?

**Comment by stuehmer** [comment]
Unfortunately the problem still exists. Now with Nextcloud 18.0.1 and Two-Factor Webauthn 0.1.2

**Comment by michib** [comment]
Strange, i tested this setup in a docker environment with the versions of postgres and nextcloud you mentioned and it worked. Are you still using postgres 11.5?

**Comment by michib** [comment]
Did you delete the table in the database manually? I didn't create a new migration (my bad) after the first nightly releases.
So could you deactivate the provider, delete the table (oc_twofactor_webauthn_registrations) and afterwards activate the provider again?

**Comment by stuehmer** [comment]
Now I did drop the table and re-activates the app. But the table is not being recreated. Is there a command to trigger it manually or do you have the create statement for Postgres for me?

**Comment by stuehmer** [comment]
My original issue is solved! Thank you for your support!

I will create a separate bug for the field length.

**Comment by michib** [comment]
Thanks for your feedback, i'm glad to hear
