### ISSUE TITLE
Official Dockerimage contains php-gmp

### ISSUE THREAD

**Issue by SuperSandro2000** [michib/nextcloud_twofactor_webauthn#24]
The official Dockerimage now contains gmp. See https://github.com/nextcloud/docker/blob/884d8c21a5fe1ddfd40897859e9d6b79ed48ac3f/18.0/apache/Dockerfile#L58 and https://github.com/nextcloud/docker/commit/7eb00b62aab4e123eec0b0a2d213396fb87c97c8

**Comment by michib** [comment]
Oh great, thanks for the notification

**Comment by michib** [comment]
I removed the section for gmp from the readme
