### ISSUE TITLE
Implement possibility to activate/deactivate webauthn devices

### ISSUE THREAD

**Issue by dr-br** [michib/nextcloud_twofactor_webauthn#26]
## THANKS
**First of all: Everything works smoothly, very nice app!**

## Question
This issue is rather a documentation request. Please move it appropriately or close it, if it does not belong here.

**My question:**  
How to add different Webauthn Devices in a straight forward manner?

**Explanation:**  
I have a Android phone, I login to my nextcloud instance, I activate the app, I configure the phone to serve as second factor, Webauthn login works.

Now I want to configure a FIDO2 stick to be my second second factor device to access nextcloud from my computer The only way to login from my computer is to use a backup code. Once logged in, I can configure my FIDO2 stick to be the second device.

Is there another possibility to add different device types? E.g. activate the app in order to register WebAuth devices but (temporarily) not enforce the second factor for login?

TNX!

**Comment by michib** [comment]
Hi,

thanks for your feedback, it's highly appreciated.

Currently it's unfortunately not possible to add but not activate a WebAuthn device. The current workflow would be like you describe it. I'm using the same Yubikey to authenticate with different android devices and then add these devices as another WebAuthn device.

But i think this would be a great enhancement to this 2FA Provider, if it would be possible to activate or deactivate added devices.

I will rename this issue to reflect the task for this feature.

**Comment by michib** [comment]
@dr-br: I uploaded a new nightly release with the requested feature. Would you be so kind to test it?

**Comment by dr-br** [comment]
Thank you for the feature! I'm currently short of time, I will test it, as soon as I can.

**Comment by dr-br** [comment]
Works as expected.
Thank you!
