### ISSUE TITLE
Database field 'credential_public_key' is too short for YubiKey 5C (and others?)

### ISSUE THREAD

**Issue by stuehmer** [michib/nextcloud_twofactor_webauthn#30]
When registering a WebAuthn Device I get an error `String data, right truncated: 7 ERROR: value too long for type character varying(255)` My `credential_public_key` from my YubiKey 5C actually needs 378 characters which is more than 255.

*Workaround:* Issuing `alter table oc_twofactor_webauthn_registrations alter credential_public_key type character varying(2500);` fixes the problem and allows me to add devices via web UI as expected.

*Version:*  Two-Factor Webauthn 0.2.0-alpha.0
*Database:* Postgresql

**Comment by michib** [comment]
Interesting, my yubikey 5 nfc worked. But yes, 255 is way to small, i will increase the size to 2000. In some fast tests the biggest public key i could produce was about 750 characters long

**Comment by michib** [comment]
I uploaded v0.2.0-alpha.1 to the appstore. It migrates the column to a length of 2000 characters.
Thanks again for your feedback, it's highly appreciated.
