### ISSUE TITLE
[BUG] Empty aaguid causes Internal Server Error on login

### ISSUE THREAD

**Issue by AdmiralNemo** [michib/nextcloud_twofactor_webauthn#36]
**Describe the bug**
After registering a new WebAuthn device, I am now unable to log in using the WebAuthn challenge.  Clicking the _Webauthn Devices_ option on the _Two-factor authentication_ screen returns an Internal Server Error.

**To Reproduce**
1. Go to Settings → Security → Two-Factor Authentication
2. Click _Add Webauthn device_
3. Touch the device, enter a name, and click _Add_
4. Log out of Nextcloud
5. Log back in, choose _Webauthn Devices_ as the two-factor authentication method

**Expected behavior**
Browser should initiate Webauthn challenge.

**Environment (feel free to add relevant information)**
 - Twofactor_Webauthn Version: 0.2.2
 - Nextcloud Version: 18.0.2
 - PHP Version: 7.3.10
 - Database with Version: PostgreSQL 11.5
 - Browser with Version: Firefox 71

**Webauthn Devices**
- Somu

**Additional context**
The `aaguid` field of the _oc_twofactor_webauthn_registrations_ table is the empty string (length 0) for any new device registered since upgrading to 0.2.2.

[nextcloud.log](https://github.com/michib/nextcloud_twofactor_webauthn/files/4363251/nextcloud.log)
[finishregister-request.txt](https://github.com/michib/nextcloud_twofactor_webauthn/files/4363276/finishregister-request.txt)
[finishregister-response.txt](https://github.com/michib/nextcloud_twofactor_webauthn/files/4363277/finishregister-response.txt)

**Comment by michib** [comment]
I'm looking into it. In the response, there is a valid uuid. As far as i could test it, it should also be converted correctly and written into the database.
It happens with all your devices or do some work? Because you are listing here only the Somu but not the Solo Tap devices.

**Comment by michib** [comment]
It's an issue with the postgresql db. Null bytes are apparently stripped. i'll have a look into it

**Comment by michib** [comment]
Ok i hope i got it finally right with the aaguid. I release 0.2.3

**Comment by AdmiralNemo** [comment]
When I tried to update to 0.2.3, I got this message:

> An error occured during the request. Unable to proceed.
> An exception occurred while executing 'UPDATE "oc_twofactor_webauthn_registrations" SET "aaguid_transform" = ?, "aaguid_transform" = ? WHERE id = ?' with params ["20202020-2020-2020-2020-202020202020", "20202020-2020-2020-2020-202020202020", 4]: SQLSTATE[42601]: Syntax error: 7 ERROR: multiple assignments to same column "aaguid_transform"

**Comment by michib** [comment]
Hopefully! i got it right this time. I just tested it with one device -_- This error occurs only with multiple devices

**Comment by michib** [comment]
@AdmiralNemo did it work this time?

**Comment by AdmiralNemo** [comment]
> @AdmiralNemo did it work this time?

Sorry, I am not sure.  I had completely removed the app and all its data and reinstalled it to get past that issue.  I have successfully upgraded to the latest version, though, and all is working correctly, now.
