### ISSUE TITLE
webauthn Fido 2 without password

### ISSUE THREAD

**Issue by tigernero79** [michib/nextcloud_twofactor_webauthn#38]
from what you understand you have implemented u2f with webauthn standard.  and this is fine for fido keys.  but the possibility of using fido2?  in practice access without a password following the webauthn standard fido2 passwordless?  2fa input and touch as 2fa without putting password will you implement it?

**Comment by michib** [comment]
Hi,
first of all, the credit for implementing the webauthn protocol goes to https://github.com/web-auth/webauthn-framework and the possibility of nextcloud to hook in a twofactor provider.

What i did was to provide the webauthn-framework as a twofactor provider for nextcloud.
Afaik passwordless or even userless login it is currently not planned by the nextcloud dev team. But for this, you have to ask them, as i am not a nextcloud developer. 

I only spoke with Cristopher Wurst about it and he told me that would require changes in the nextcloud authentication module.
