### ISSUE TITLE
[BUG] Using Webauthn limits possibility of using WebDav

### ISSUE THREAD

**Issue by Blacksheep70** [michib/nextcloud_twofactor_webauthn#39]
**Describe the bug**
With Two-Factor Webauthn activated it is impossible to sync calendar e.g. into Thunderbird

**To Reproduce**
Activate Two-Factor Webauthn 
Access the Nextcloud Calendar through a 3rd Party application usig WebDAV, e.g. Thunderbird
Authentication fails as WebDav seems not to support Webauthn

**Expected behavior**
Using normal authentication (User/Password) method when accessing WebDAV interface

**Environment (feel free to add relevant information)**
 - Twofactor_Webauthn Version:  0.2.4
 - Nextcloud Version: 19
 - PHP Version: 7.2.24
 - Database with Version: mysqld  Ver 5.7.30-
 - Browser with Version: Firefox 76.0.1 (64-Bit)
 - OS: Linux (Server) / Windows (Client)

Device is paired and works in general
<img width="423" alt="Unbenannt" src="https://user-images.githubusercontent.com/8124924/83662354-a7c4f800-a5c7-11ea-98f7-afd37b4b83ca.PNG">

When accessing the Nextcloud Calendar via WebDav interface authentication is not possible as it does not support Webauthn:
<img width="452" alt="Unbenannt1" src="https://user-images.githubusercontent.com/8124924/83663166-c4156480-a5c8-11ea-9349-d790178c0db9.PNG">

**Webauthn Devices**
Ledger Nano X with Fido U2F module (works fine for authentication via Webauthn)

**Comment by karottenbaum** [comment]
You need to use app passwords instead. To create one, scroll all the way down on the "Security" page for this field:
![grafik](https://user-images.githubusercontent.com/6024426/83679253-5aed1b80-a5df-11ea-82c9-d37dd6bd9801.png)

**Comment by Blacksheep70** [comment]
Thank you for your help.

Followed your advise but the calendar deactivates then in the application (here Thunderbird). I created an App Password called "Thunderbird" and used the created login user for Thundebird. However, it looks like the WebDAV connect itself is being blocked as the calendar is deactivating before a password is queried.

I also tried to drop the config for the Nextcloud Calendar entry in Thunderbird and created a new one. Same appears here.

Here is what the log is telling:

`

Debug | webdav | OCA\DAV\Connector\Sabre\Exception\PasswordLoginForbidden: /storage/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php - line 106: OCA\DAV\Connector\Sabre\Auth->validateUserPass("*** sensiti ... *")/storage/var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php - line 254: Sabre\DAV\Auth\Backend\AbstractBasic->check(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})/storage/var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php - line 156: OCA\DAV\Connector\Sabre\Auth->auth(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})/storage/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php - line 193: OCA\DAV\Connector\Sabre\Auth->check(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})/storage/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php - line 144: Sabre\DAV\Auth\Plugin->check(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})/storage/var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89: Sabre\DAV\Auth\Plugin->beforeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})/storage/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 458: Sabre\DAV\Server->emit("beforeMethod:PROPFIND", [ Sabre\HTTP ... }])/storage/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 251: Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})/storage/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 319: Sabre\DAV\Server->start()/storage/var/www/html/nextcloud/apps/dav/lib/Server.php - line 320: Sabre\DAV\Server->exec()/storage/var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php - line 35: OCA\DAV\Server->exec()/storage/var/www/html/nextcloud/remote.php - line 167: require_once("/storage/va ... p")
-- | -- | --




`

**Comment by Blacksheep70** [comment]
Did further research:

Mounting the WebDAV in Windows works fine using
`net use Z: https://<domain>/nextcloud/remote.php/dav/files/<User>/ /user:<User>`
with the App User &Password created under App-Password

**Comment by michib** [comment]
@karottenbaum: Thanks for your additional support :-)

@Blacksheep70: I'm not sure if this is an issue of this twofactor provider. Would you be so kind and test if the issue also occurs if you deactivate the webauthn twofactor provider and test it instead with another provider? For example with the totp provider: https://docs.nextcloud.com/server/19/user_manual/user_2fa.html?highlight=totp

**Comment by Blacksheep70** [comment]
@michib: I configured TOTP and have exactly the same issue

`

Debug | webdav | OCA\DAV\Connector\Sabre\Exception\PasswordLoginForbidden: /storage/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php - line 106: OCA\DAV\Connector\Sabre\Auth->validateUserPass("*** sensiti ... *")/storage/var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php - line 254: Sabre\DAV\Auth\Backend\AbstractBasic->check(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})/storage/var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php - line 156: OCA\DAV\Connector\Sabre\Auth->auth(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})/storage/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php - line 193: OCA\DAV\Connector\Sabre\Auth->check(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})/storage/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php - line 144: Sabre\DAV\Auth\Plugin->check(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})/storage/var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89: Sabre\DAV\Auth\Plugin->beforeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})/storage/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 458: Sabre\DAV\Server->emit("beforeMethod:PROPFIND", [ Sabre\HTTP ... }])/storage/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 251: Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})/storage/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 319: Sabre\DAV\Server->start()/storage/var/www/html/nextcloud/apps/dav/lib/Server.php - line 320: Sabre\DAV\Server->exec()/storage/var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php - line 35: OCA\DAV\Server->exec()/storage/var/www/html/nextcloud/remote.php - line 167: require_once("/storage/va ... p")
-- | -- | --
`
Of course I used the configured App-Password 

So we can assume that when Webauthn or TOTP is activated 'external' logons are prohibited.

So am I right assuming that the issue is not module (TOTP, Webauthn) specific? From the log I would interpret that the "sabre" code in the WebDAV module is rejecting the logon. What is your opinion to whom this issue needs to be adressed?

**Comment by michib** [comment]
Yes it seems you have to file an issue for sabre. But i don't know anything about sabre, so its more like an educated guess.

I'm not sure and i couldn't find it in the documentation. Maybe an app password can only used by one client? There are systems where the app password is registered to a specific client after the first login. So did you try to create a fresh app password for this client?
