### ISSUE TITLE
Support NextCloud 19

### ISSUE THREAD

**Issue by gergelypolonkai** [michib/nextcloud_twofactor_webauthn#40]
**Is your feature request related to a problem? Please describe.**
According to the app store, this addon is untested with NextCloud 19.

**Describe the solution you'd like**
Make it appear as tested so users can install it without stressing about the “Unstressed” word.

**Additional context**
I probably didn’t test every aspect of the app, but it seems working for me under 18.0.6.

**Comment by umglurf** [comment]
Seems this is now build in with the password less function in Nexcloud 19: https://nextcloud.com/blog/nextcloud-hub-brings-productivity-to-home-office/

**Comment by gergelypolonkai** [comment]
@umglurf no, they are not the same. Passwordless function means you don’t need your password. 2nd factor means you need your password **and** a 2nd factor (in this case, a WebAuthn device, like a Nitrokey or YubiKey).

**Comment by umglurf** [comment]
That's right, was a bit quick there.

**Comment by michib** [comment]
It should be the exactly same technique, but it seems not to be a 2fa. i will look into it tomorrow

**Comment by beerisgood** [comment]
Any status update?

**Comment by michib** [comment]
Sorry for the late reply, to busy after my holidays ;-)

I finally tested it for NC19 and found no issues for my setup.

The passwordless function is technically the same request to a webauthn device as for this 2FA provider. But i could not find a possibility to use the passwordless feature as 2FA provider.
