### ISSUE TITLE
[BUG] does not remove webauthn section in security section

### ISSUE THREAD

**Issue by tigernero79** [michib/nextcloud_twofactor_webauthn#43]
the entry "Authentication without password

  Configure your account for passwordless authentication following the FIDO2 standard.
  No devices configured.

  Add WebAuthn device

  "

is not deleted by deleting or disabling application in nextcloud 19.0.1

![Screenshot_20200806-203113_Chrome](https://user-images.githubusercontent.com/35575744/89568680-f0956900-d823-11ea-992e-c7af036cb06a.jpg)

**Comment by PatrickJosh** [comment]
This is not a feature of this app but of the Nextcloud 19 server. This app has nothing to do with this.

**Comment by tigernero79** [comment]
Ah ok sorry
