### ISSUE TITLE
Two-Factor Webauthn login not possible with iOS14

### ISSUE THREAD

**Issue by manolo4711** [michib/nextcloud_twofactor_webauthn#44]
No Webauthn login possbile with my iPad running on iOs 14 Public beta 7

I can register my iPad with iOS14 but if I want to login I got the safari message, please put in your security device. 

Github 2 factor Webauthn works with Safari 14. Here I can choose my ipad (FaceID) as an security device. 

 - Twofactor_Webauthn Version: 0.25
 - Nextcloud Version: 18.0.8
 - PHP Version: 7.3

**Webauthn Devices**
Please list here your webauthn devices, which relate to the issue, eg:
- iPad with iOS 14 Public beta 7

It will be nice, if the nextcloud Webauth plugin will also support Safari 14.... Thanks.

**Comment by michib** [comment]
Hi,
sorry for the late reply, i'm currently not really active when it comes to coding after work.
Sadly i'm not able to support iOS as i don't own a Mac.
But if you could provide a pullrequest with a fix, i will gladly check it.

**Comment by michib** [comment]
This issue should be fixed with version 0.2.13. Please reopen if its not the case.
