### ISSUE TITLE
Version 20 Compatibility

### ISSUE THREAD

**Issue by sunjam** [michib/nextcloud_twofactor_webauthn#45]
Thank for considering Version 20 Compatibility

**Comment by Dark-Schnitzel** [comment]
This Version is compatible with Nextcloud 20. Tested with 20.0.2. and an Android Client as webauthn device for 2FA.
This needs to be changed in appinfo/info.xml:


-        <nextcloud min-version="16" max-version="19" />
+        <nextcloud min-version="16" max-version="20" />

**Comment by j-4** [comment]
@michib it would be awesome if you could raise the version and publish this release to the app store. The "incompatibility" keeps the instances from auto-upgrading to nextcloud 20. Thanks a lot for your efforts!

**Comment by michib** [comment]
did a simple upgrade work for you? it's not working in my test instances, i can't login with my preconfigured keys
