### ISSUE TITLE
[BUG] Can't add any WebAuthn device

### ISSUE THREAD

**Issue by scriptkiddy3** [michib/nextcloud_twofactor_webauthn#47]
First of all thanks for you hard work guy
Im kinda new to nextcloud so sorry if thats a dumb issue :)

I can't add any Web Authn devices with chrome of firefox

Click on Add WebAuthn device

**Expected behavior**
I expect Nextcloud to pickup my yubikey as a webauthn device

**Screenshots**
This shows up 1 sec 
![2](https://user-images.githubusercontent.com/76011161/103056053-e7563000-4569-11eb-9368-34933fd7f504.PNG)
and it goes back to
![1](https://user-images.githubusercontent.com/76011161/103056075-f3da8880-4569-11eb-8e49-6353b2cdee8f.PNG)

**Environment (feel free to add relevant information)**
 - Twofactor_Webauthn Version:  0.2.6 
 - Nextcloud Version: 20.0.2
 - PHP Version: 7.4.3
 - Browser with Version: Chrome 87.0.4280.88 or Firefox 84.0.1
 - OS: Ubuntu 20.04.1 LTS

**Webauthn Devices**
- Yubikey 5c
- Yubikey 5 NFC

**Browser error log**
`SecurityError This is an invalid domain.
(anonymous) @ AddDevice.vue:114
Promise.catch (async)
start @ AddDevice.vue:113
Ge @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
s._wrapper @ vue.runtime.esm.js:6917`

**Additional context**
I feel like the issue is that I run the nextcloud server locally (10.0.0.136) and I run it with a self-signed ssl certificate..but idk

**Comment by karottenbaum** [comment]
WebAuthn [by specification (7.)](https://www.w3.org/TR/webauthn/#sctn-createCredential) can only be used on sites with a domain name, there's nothing twofactor_webauthn can do about that I'm afraid :(. Bare IPs like https://10.0.0.136 won't work.

**Comment by scriptkiddy3** [comment]
> As I understand it, WebAuthn [by specification (7.)](https://www.w3.org/TR/webauthn/#sctn-createCredential) can only be used on sites with a domain name, there's nothing twofactor_webauthn can do about that I'm afraid :(. Bare IPs like https://10.0.0.136 won't work.

Ahhhhhhh I didnt get that part, tyvm for your help :)
