### ISSUE TITLE
[BUG] Could not extract app twofactor_webauthn

### ISSUE THREAD

**Issue by mark0n** [michib/nextcloud_twofactor_webauthn#48]
App fails to install on my Nextcloud server with the following error:
```
$ sudo -u www-data php occ app:install twofactor_webauthn
Error: Could not extract app twofactor_webauthn
```
Installing through the web front-end results in the same error. Other apps install fine.

**Environment**
 - Nextcloud Version: 19.0.8
 - PHP Version: 7.3.19
 - Database with Version: MariaDB 10.3.27
 - OS: Debian 10 (buster)

**Nextcloud error log**
No related errors in `nextcloud.log`.

**Comment by coelner** [comment]
Dito for:
-    Nextcloud Version: 20.0.6
-    PHP Version: 7.3.19-1~deb10u1
-    Database with Version: MariaDB 10.3.27
-    OS: Debian 10 (buster)

**Comment by QuesarVII** [comment]
I have the same issue on CentOS 8 w/ php 7.3.20.  I added an error_log line to the _error function in 3rdparty/pear/archive_tar/Archive/Tar.php and was able to capture this error from the extract function:

Out-of-path file extraction {/tmp/oc_tmp_hVL5xf-folder/twofactor_webauthn/vendor/bin/doctrine-dbal --> ../doctrine/dbal/bin/doctrine-dbal}

**Comment by QuesarVII** [comment]
This looks like it might be a bug with Archive_Tar introduced with this commit: https://github.com/pear/Archive_Tar/commit/cde460582ff389404b5b3ccb59374e9b389de916#diff-8b265231ddc3289c7d5e2c9abc3c70d3b333b0b9e3e084e6d088a09bec297ff9

I'm reporting it to them and referencing this bug now.

**Comment by mark0n** [comment]
I have installed version 1:1.10.12+submodules+notgz+20210212-1 from bullseye. I confirmed the change @QuesarVII referred to is actually contained in `/usr/share/php/Archive/Tar.php` but I still see this error.

In the meantime I have upgraded to Nextcloud 20.0.7 but that didn't make a difference either.
