### ISSUE TITLE
Nextcloud 21 Support

### ISSUE THREAD

**Issue by sunjam** [michib/nextcloud_twofactor_webauthn#49]
Please add support.  Thanks!

**Comment by Dark-Schnitzel** [comment]
Seems to be that only the Version in appinfo/info.xml must be bumped to 21. Tested with Nextcloud 21 and php73, works without problems in Chromium with a Nitrokey.

Same as with Version 20, upstream is bit slow sadly.
https://github.com/michib/nextcloud_twofactor_webauthn/issues/45

**Comment by michib** [comment]
@sunjam Thanks to pointing out that nextcloud 21 was released. I was not aware of it.

@Dark-Schnitzel Thanks for Testing with Nitrokey

I'm aware that i am not very active on this project, as it depends on my free time, my mood to work on it after a full day of coding for work, my health and a lot of other interests. But the conditions for working on this project are rarely met, so it won't change any time soon.
But as it is an open source project, feel free to provide pullrequests or even using an own version of this project.

Best regards
