### ISSUE TITLE
[BUG] Cannot add Webauthn Devices

### ISSUE THREAD

**Issue by bones1014** [michib/nextcloud_twofactor_webauthn#55]
**Describe the bug**
When trying to add a Webauthn Device the button just flashes briefly but won't start adding a device.

**To Reproduce**
1. Go to Security under Personal
2. Click on Add Webauthn Device

**Expected behavior**

**Screenshots**

**Environment (feel free to add relevant information)**
 - Twofactor_Webauthn Version: 0.2.9
 - Nextcloud Version: snap 20.0.9
 - PHP Version: 7.4.15
 - Database with Version: mysql 5.7.34
 - Browser with Version: Opera 76.0.4017.94 and chrome 90.0.4430.93 (Official Build) (64-bit)
 - OS: Windows 10 build 19042.964

**Webauthn Devices**
Please list here your webauthn devices, which relate to the issue, eg:
- Yubikey 5 NFC
- Windows Hello

**Nextcloud error log**
Please attach the nextcloud error log, if applicable

**Browser error log**
Please attach the error from the developer console of the browser, if applicable

**Additional context**

Error | index | Exception: Argument 1 passed to OC\Core\Controller\WebAuthnController::finishAuthentication() must be of the type string, null given, called in /snap/nextcloud/27434/htdocs/lib/private/AppFramework/Http/Dispatcher.php on line 169
-- | -- | --

**Comment by michib** [comment]
Hi @bones1014,

i'm not able to reproduce the issue. It works for me. But from the logmessage, it looks like you are trying to setup a first factor authentication with your yubikey? Thats not related to this twofactor provider, the firstfactor authentication is provided by nextcloud itself.

If it happens on setting up a key for this twofactor provider, could you provide more information how to reproduce the issue?

**Comment by isdnfan** [comment]
Just tested successfully using latest docker NC 21.0.2 (version from 04.06.2021) and Two-Factor Webauthn 0.2.10

**Comment by bones1014** [comment]
I'll give it another try since my snap updated recently. Thanks for looking!

**Comment by bones1014** [comment]
There hasn't been any change to the way the app is behaving. I've removed and reinstalled the app and it still doesn't allow me to add a webaunth device. I've tried in different browsers and they are all the same.

**Comment by michib** [comment]
Is it still the same error Message?

**Comment by bones1014** [comment]
It doesn't give any error message. It just doesn't allow me to add a device. It just flashes to the graphic like it's going to add one and then just goes back to the add button.

**Comment by michib** [comment]
Could you provide a screenshot of what you are trying to do?

**Comment by bones1014** [comment]
![image](https://user-images.githubusercontent.com/74389768/127905231-8baf8e74-4a7b-45db-b36a-bf43d36f887b.png)
That button just flashes to "please plug in...." It's too fast to read. The box to add a device doesn't appear.

**Comment by michib** [comment]
And there is no further error entry in the nextcloud log? 
Could you check the console of your browser? You can open it with pressing F12. Can you check if there is some error message (or anything other) logged?

**Comment by bones1014** [comment]
<template>
	<div v-if="!isHttps">
		{{ t('settings', 'Passwordless authentication requires a secure connection.') }}
	</div>
	<div v-else>
		<div v-if="step === RegistrationSteps.READY">
			<button @click="start">
				{{ t('settings', 'Add WebAuthn device') }}
			</button>
		</div>

		<div v-else-if="step === RegistrationSteps.REGISTRATION"
			class="new-webauthn-device">
			<span class="icon-loading-small webauthn-loading" />
			{{ t('settings', 'Please authorize your WebAuthn device.') }}
		</div>

		<div v-else-if="step === RegistrationSteps.NAMING"
			class="new-webauthn-device">
			<span class="icon-loading-small webauthn-loading" />
			<input v-model="name"
				type="text"
				:placeholder="t('settings', 'Name your device')"
				@:keyup.enter="submit">
			<button @click="submit">
				{{ t('settings', 'Add') }}
			</button>
		</div>

		<div v-else-if="step === RegistrationSteps.PERSIST"
			class="new-webauthn-device">
			<span class="icon-loading-small webauthn-loading" />
			{{ t('settings', 'Adding your device …') }}
		</div>

		<div v-else>
			Invalid registration step. This should not have happened.
		</div>
	</div>
</template>

<script>
import confirmPassword from '@nextcloud/password-confirmation'

import logger from '../../logger'
import {
	startRegistration,
	finishRegistration,
} from '../../service/WebAuthnRegistrationSerice'

const logAndPass = (text) => (data) => {
	logger.debug(text)
	return data
}

const RegistrationSteps = Object.freeze({
	READY: 1,
	REGISTRATION: 2,
	NAMING: 3,
	PERSIST: 4,
})

export default {
	name: 'AddDevice',
	props: {
		httpWarning: Boolean,
		isHttps: {
			type: Boolean,
			default: false,
		},
	},
	data() {
		return {
			name: '',
			credential: {},
			RegistrationSteps,
			step: RegistrationSteps.READY,
		}
	},
	methods: {
		arrayToBase64String(a) {
			return btoa(String.fromCharCode(...a))
		},
		start() {
			this.step = RegistrationSteps.REGISTRATION
			console.debug('Starting WebAuthn registration')

			return confirmPassword()
				.then(this.getRegistrationData)
				.then(this.register.bind(this))
				.then(() => { this.step = RegistrationSteps.NAMING })
				.catch(err => {
					console.error(err.name, err.message) 
                                        //there is a red x next to the above entry
					this.step = RegistrationSteps.READY
				})
		},

		getRegistrationData() {
			console.debug('Fetching webauthn registration data')

			const base64urlDecode = function(input) {
				// Replace non-url compatible chars with base64 standard chars
				input = input
					.replace(/-/g, '+')
					.replace(/_/g, '/')

				// Pad out with standard base64 required padding characters
				const pad = input.length % 4
				if (pad) {
					if (pad === 1) {
						throw new Error('InvalidLengthError: Input base64url string is the wrong length to determine padding')
					}
					input += new Array(5 - pad).join('=')
				}

				return window.atob(input)
			}

			return startRegistration()
				.then(publicKey => {
					console.debug(publicKey)
					publicKey.challenge = Uint8Array.from(base64urlDecode(publicKey.challenge), c => c.charCodeAt(0))
					publicKey.user.id = Uint8Array.from(publicKey.user.id, c => c.charCodeAt(0))
					return publicKey
				})
				.catch(err => {
					console.error('Error getting webauthn registration data from server', err)
					throw new Error(t('settings', 'Server error while trying to add WebAuthn device'))
				})
		},

		register(publicKey) {
			console.debug('starting webauthn registration')

			return navigator.credentials.create({ publicKey })
				.then(data => {
					this.credential = {
						id: data.id,
						type: data.type,
						rawId: this.arrayToBase64String(new Uint8Array(data.rawId)),
						response: {
							clientDataJSON: this.arrayToBase64String(new Uint8Array(data.response.clientDataJSON)),
							attestationObject: this.arrayToBase64String(new Uint8Array(data.response.attestationObject)),
						},
					}
				})
		},

		submit() {
			this.step = RegistrationSteps.PERSIST

			return confirmPassword()
				.then(logAndPass('confirmed password'))
				.then(this.saveRegistrationData)
				.then(logAndPass('registration data saved'))
				.then(() => this.reset())
				.then(logAndPass('app reset'))
				.catch(console.error.bind(this))
		},

		async saveRegistrationData() {
			try {
				const device = await finishRegistration(this.name, JSON.stringify(this.credential))

				logger.info('new device added', { device })

				this.$emit('added', device)
			} catch (err) {
				logger.error('Error persisting webauthn registration', { error: err })
				throw new Error(t('settings', 'Server error while trying to complete WebAuthn device registration'))
			}
		},

		reset() {
			this.name = ''
			this.registrationData = {}
			this.step = RegistrationSteps.READY
		},
	},
}
</script>

<style scoped>
	.webauthn-loading {
		display: inline-block;
		vertical-align: sub;
		margin-left: 2px;
		margin-right: 2px;
	}

	.new-webauthn-device {
		line-height: 300%;
	}
</style>

**Comment by bones1014** [comment]
[New Text Document (3).txt](https://github.com/michib/nextcloud_twofactor_webauthn/files/6918891/New.Text.Document.3.txt)

**Comment by michib** [comment]
That are the contents of the console? To be honest, i doubt that. That's the sourcecode of the page

**Comment by michib** [comment]
Please provide a screenshot of what you just copied. Maybe i can point you to the right direction afterwards.

**Comment by bones1014** [comment]
When I have the console open and then click the Add Webauthn Device button I get this:
![image](https://user-images.githubusercontent.com/74389768/127908236-fe208f69-4dd7-44cb-ae78-b6c40bcd89e8.png)

**Comment by michib** [comment]
Do you have you installation provided by https?

**Comment by bones1014** [comment]
I thought I did. I was primarily accessing it on my local network and I guess it didn't like the HTTPS. I just went through the web address with is running HTTPS and has no problem and it's working. huh, I didn't think about that. Thanks for the guidance.

**Comment by michib** [comment]
Ah alright. Thanks for the feedback. I will add some error handling for this. Webauthn only works through https by spec, the browsers restrict http connections.

**Comment by Muzosh** [comment]
Hello @michib,

I'm having a same issue as the original author of this issue: after clicking on the [button](https://github.com/michib/nextcloud_twofactor_webauthn/issues/55#issuecomment-891229355) a small loading circle shows up for a split second and then disappears and nothing happens.

Immediately after clicking on the button there is a message "starting webauthn registration" and it is followed by this error:
![image](https://user-images.githubusercontent.com/30979983/140662031-7bf71b4f-6d93-41e1-ba2a-17eb43c07979.jpeg)

It is logged right here:
![image](https://user-images.githubusercontent.com/30979983/140662043-fc035a18-e312-4be8-847f-1cb991d3935e.jpeg)


BTW, I did not even tried to register any webauthn device, I just freshly installed this provider and tried to click on that button.
Nextcloud version: 21.0.2 and tried also with 21.0.5

**Comment by michib** [comment]
@Muzosh i think the error message indicates, that you should check your nextcloud setup. It has to run on a https connection. But i don't know what this error message exactly means. You can try to install the new released version 0.2.12 and provide the logs of the browser console and the server logs here.

**Comment by michib** [comment]
@Muzosh could you retry with version 0.2.13 and post the console entries of your browsers? Please remove any sensitive data before!

**Comment by Muzosh** [comment]
@michib Here is the result of clicking the button after updating to 0.2.13:
![image](https://user-images.githubusercontent.com/30979983/144236295-7506b672-a83d-412f-a1d2-3e8e79224c68.jpeg)

As you have said, I'm running nextcloud on my own testing server with self-signed certificate. It is https connection but with invalid certificate that I had to allow when first connected to this server. So my problem might be in wrong configuration of the server. 

Thanks anyway, I wanted to test your app because I'm creating a different two-factor as well.

**Comment by michib** [comment]
Yes localhost does not work in every browser afaik. For my development testing i am using a local domain like "cloud.net.local". Browsers are happy with it :-)
In this case i am closing the issue, please reopen or open another bug if it turns out that the issue is part of the provider and not of the server configuration.
