### ISSUE TITLE
[BUG] (probable, needs triage) files_encryption not having access to files on the GUI using WebAuthn for authentication

### ISSUE THREAD

**Issue by noseshimself** [michib/nextcloud_twofactor_webauthn#64]
**Describe the bug**
Using "Authenticate using a Device" I am still asked for a username and and asked to use my device to authenticate.  At the next step I'm choosing WebAuthn as SFA method. 

After logging in I'm greeted with the message

"Invalid private key for encryption app. Please update your private key password in your personal settings to recover access to your encrypted files.✖"

I'm using a Feitian K33 (BLE) (which can handle FIDO and FIDO2 using USB or BLE).

This is not happening using Windows Hello for the process which I'm not really understanding. At all.

**To Reproduce**
1) Activate files_encryption on your Nextcloud installation.
2) Register a WebAuthn device as SFA as well as passwordless login device (not sure if it is necessary but that's what I did)
3) Log in "using a device"
4) Use the same device for SFA

**Expected behavior**
This is actually what I expect to happen if I do not enter the password necessary to decrypt the stuff....

BUT: I expected the authenticator to provide an alternative way for providing access to files (even if that means carrying additional keys for the files like they were shared between users).

**Environment (feel free to add relevant information)**
 - Twofactor_Webauthn Version: 0.2.10
 - Nextcloud Version: 19.0.7
 - PHP Version:	7.4.20
 - Database with Version: mysql 10.4.12
 - Browser with Version: (any Firefox, Chromw, Safari
 - OS: Windows, Linux

**Webauthn Devices**
Please list here your webauthn devices, which relate to the issue, eg:
- Feitian K33
- Windows Hello

**Additional context**
I suppose there has to be a way to get access to that key after logging in (e. g. still entering it somewhere) or refuse "log in using a device" on installations with file encryption.

**Comment by michib** [comment]
Hi sorry for the late reply, somehow the notification Mail didnt show up. Unfortunately this is the wrong project. For the first factor webauthn authentication, please refer to https://github.com/nextcloud/server.
Also this project isn't related to any encryption, but for this i don't know where to refer to.
This project only provides the second factor authentication.
