### ISSUE TITLE
Support for NC 22

### ISSUE THREAD

**Issue by JimmyKater** [michib/nextcloud_twofactor_webauthn#68]
pls add support for NC22.

Thanks in advance :-)

**Comment by michib** [comment]
i'm looking into it. Sadly it doesn't work with the current implementatation, the security key can be added but it isn't requested during login

**Comment by kowalski7cc** [comment]
That's strange, I'm using it without issues on Nextcloud 22.1.1

**Comment by michib** [comment]
@kowalski7cc Did it work for an user that didn't have twofactor auth enabled? Thats my issue, i'm setting up a new user, registering a security key but can still login withouth the key. Twofactor auth didn't get enabled for the user.

**Comment by kowalski7cc** [comment]
Tomorrow I'll try to provision a new user and add only webauthn 2fa

**Comment by michib** [comment]
Thank you! But it seems my development environment somehow got messed up. It doesn't even work with NC 21, but there i know it did.

**Comment by kowalski7cc** [comment]
Tried on my NC22, it seems ok even with a fresh user wich only deployed webauthn.
