### ISSUE TITLE
[BUG] Webauthn will end in loop on iOS

### ISSUE THREAD

**Issue by techsolo12** [michib/nextcloud_twofactor_webauthn#71]
**Describe the bug**
When i want to login in my cloud over my iPhone or iPad. I will get stuck in a loop.
This issue comes on safari and firefox and only on iOS.
On every other device i can login without any issues. MacBook or linux machine or windows laptop or android smartphone.

**To Reproduce**
1. Go to cloud
2. Enter login credentials
3. Choose Webauthn
4. Page reloads
5. Choose Webauthn
6. Page relaods

**Expected behavior**
Get a message like "enter your hardware key to login bla bla"

**Environment (feel free to add relevant information)**
 - Twofactor_Webauthn Version: 0.2.11
 - Nextcloud Version: 22.1.1
 - PHP Version: 7.4
 - OS: iOS 15.0.0

**Webauthn Devices**
Please list here your webauthn devices, which relate to the issue, eg:
- Yubikey 5 NFC
- yubikey 5 C

**Nextcloud error log**

Exception: Argument 1 passed to OC\Core\Controller\WebAuthnController::finishAuthentication() must be of the type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 217

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 156:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.php - line 301:

    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.php - line 1000:

    OC\Route\Router->match()

    /var/www/nextcloud/index.php - line 36:

    OC::handleRequest()

Verursacht durch TypeError: Argument 1 passed to OC\Core\Controller\WebAuthnController::finishAuthentication() must be of the type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 217

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:

    OC\Core\Controller\WebAuthnController->finishAuthentication()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 156:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.php - line 301:

    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.php - line 1000:

    OC\Route\Router->match()

    /var/www/nextcloud/index.php - line 36:

    OC::handleRequest()

**Comment by michib** [comment]
This issue is probably fixed with version 0.2.13. Please reopen if its not the case.

**Comment by techsolo12** [comment]
I can confirm the update fix the loop.
I can login on my iphone and ipad with my yubikey 5 usb c and yubikey 5 nfc.
Thanks for your help and the work on this app!
