### ISSUE TITLE
[BUG] Incompatible with PHP < 7.4

### ISSUE THREAD

**Issue by tcitworld** [michib/nextcloud_twofactor_webauthn#72]
**Describe the bug**
Composer seem to require PHP 7.4.

**To Reproduce**
1. Update nextcloud_twofactor_webauthn to 0.2.12 on PHP 7.3, which is supported by NC 21.
2. Nextcloud is broken with the following error: `Your Composer dependencies require a PHP version ">= 7.4.0".`.

**Environment (feel free to add relevant information)**
 - Twofactor_Webauthn Version: 0.2.12
 - Nextcloud Version: 21.0.7
 - PHP Version: 7.3

Should be fixed by adding the following into `composer.json`:
```json
"config": {
        "platform": {
            "php": "7.3"
        },
    },
```
https://andy-carter.com/blog/composer-php-platform

**Comment by michib** [comment]
Thank you @tcitworld for reporting this bug and providing the solution :-) I hope version 0.2.13 fixes it for you?

**Comment by tcitworld** [comment]
I confirm it does, thanks!

**Comment by michib** [comment]
Great, thank you for your feedback
